[project]
name = "analyzelblogs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.42.43",
    "dotenv>=0.9.9",
    "openpyxl>=3.1.5",
    "pandas>=3.0.0",
]
